# Generated by Django 3.2.9 on 2021-11-09 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Product Catagorys',
                'verbose_name_plural': 'Catagorys',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimage', models.ImageField(upload_to='product')),
                ('name', models.CharField(max_length=264)),
                ('preview_text', models.TextField(max_length=264, verbose_name='Preview Text ')),
                ('detail_text', models.TextField(max_length=1000, verbose_name='Descriptions')),
                ('price', models.FloatField()),
                ('old_price', models.FloatField(default=0.0)),
                ('crate_date', models.DateTimeField(auto_now_add=True)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catagory', to='Product_App.catagory')),
            ],
            options={
                'verbose_name': 'Products',
                'verbose_name_plural': 'Products List',
                'ordering': ['-crate_date'],
            },
        ),
    ]
