# Generated by Django 3.2.9 on 2021-11-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['-crate_date'], 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='catagory',
            name='geeks_field',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
