# Generated by Django 3.2.9 on 2021-11-09 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product_App', '0002_auto_20211110_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catagory',
            name='geeks_field',
        ),
    ]
