# Generated by Django 3.2.9 on 2021-11-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_App', '0003_remove_catagory_geeks_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='product'),
        ),
        migrations.AddField(
            model_name='products',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='product'),
        ),
        migrations.AddField(
            model_name='products',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='product'),
        ),
    ]
