# Generated by Django 3.2.9 on 2021-11-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_App', '0004_auto_20211110_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
