# Generated by Django 3.2.9 on 2021-11-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_App', '0005_alter_products_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='more_img',
            field=models.BooleanField(default=False),
        ),
    ]
