# Generated by Django 3.2.9 on 2021-11-17 07:50

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_App', '0006_products_more_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='detail_text',
            field=djrichtextfield.models.RichTextField(max_length=1000, verbose_name='Descriptions'),
        ),
    ]
