# Generated by Django 3.2.9 on 2021-11-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_App', '0002_alter_profile_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, choices=[('DHAKA', 'DHAKA'), ('RANGPUR', 'RANGPUR'), ('RAJSHIE', 'RAJSHIE'), ('KULNA', 'KULNA'), ('BORISAL', 'BORISAL')], default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, choices=[('BSANGLADESH', 'BSANGLADESH'), ('INDA', 'INDA')], max_length=60, null=True),
        ),
    ]
