# Generated by Django 3.2.9 on 2021-11-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_App', '0003_auto_20211108_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, choices=[('DHAKA', 'DHAKA'), ('RANGPUR', 'RANGPUR'), ('RAJSHIE', 'RAJSHIE'), ('KULNA', 'KULNA'), ('BORISAL', 'BORISAL')], default='DHAKA', max_length=60, null=True),
        ),
    ]
